server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: shafin
    password: shafin
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
